#!/bin/zsh

problem=gauss
CFL=${1:-0.05}
id=${problem}-${CFL}
errorfile=data/${problem}.err
l1errorimg=img/l1-error-${id}.pdf
l1_xerrorimg=img/l1_x-error-${id}.pdf
logfile=log

make clean
rm -f ${log} ${errorfile}

sed -i "s/PROBLEM = .*/PROBLEM = ${problem}/" Makefile
sed -i "5c #include \"${problem}.h\"" sode1-main.cpp
sed -i "s/cfl = .*/cfl = ${CFL}/" sode1.fmr
sed -i "s/cfl = .*/cfl = ${CFL};/" sode1-main.cpp
head -5 sode1-main.cpp
grep "cfl =" sode1.fmr sode1-main.cpp

docker run -it --rm -v $PWD:/work -u $UID:$GID ishiy1993/formura-bin ./run-100-1000 ${logfile}

l1factor0=$(awk '/^0.10/{print $5}' ${errorfile})
ploton --xl "dt" --yl "error" --yf "10^{%L}" --logx --logy \
       --output "${l1errorimg}" \
       "#1 u 4:5 with points, ${l1factor0}*(x/0.1)**4" ${errorfile} |
xargs cp2server

l1_xfactor0=$(awk '/^0.10/{print $6}' ${errorfile})
ploton --xl "dt" --yl "error" --yf "10^{%L}" --logx --logy \
       --output "${l1_xerrorimg}" \
       "#1 u 4:6 with points, ${l1_xfactor0}*(x/0.1)**4" ${errorfile} |
xargs cp2server
