#!/bin/zsh

problem=gauss
CFL=${1:-0.1}
logfile=log
masserrordata=mass-error-${problem}-${CFL}.dat
masserrorimg=img/mass-error-${problem}-${CFL}.pdf
maxerrordata=max-error-${problem}-${CFL}.dat
maxerrorimg=img/max-error-${problem}-${CFL}.pdf

make clean
rm -f ${log} ${masserrordata} ${maxerrordata}

sed -i "s/PROBLEM = .*/PROBLEM = ${problem}/" Makefile
sed -i "5c #include \"${problem}.h\"" normal-4th-main.cpp
sed -i "s/cfl = .*/cfl = ${CFL}/" normal-4th.fmr
sed -i "s/cfl = .*/cfl = ${CFL};/" normal-4th-main.cpp
head Makefile normal-4th-main.cpp
grep "cfl =" normal-4th.fmr normal-4th-main.cpp

docker run -it --rm -v $PWD:/work -u $UID:$GID ishiy1993/formura-bin ./run-100-1000 ${logfile} ${masserrordata}

massfactor=$(awk '/^0.10/{print $4}' ${masserrordata})
ploton --xl dx --yl "total mass error" --yf "%.1E" --logx --logy \
       --output "${masserrorimg}" \
       "#1 u 1:4 with linespoints, ${massfactor}*(x/0.1)**4, ${massfactor}*(x/0.1)**8" ${masserrordata} |
xargs cp2server

ls data/* | grep "${problem}-${CFL}-.*-100.dat" | xargs grep '^.*$' |
awk '{print $1,sqrt(($2-$5)**2)/$5}' |
tr ':' ' ' | sed "s/^.*${problem}-${CFL}-//" | sed 's/-100.dat//' |
awk '{if(a[$1] < $3){a[$1]=$3}}END{for(k in a){printf("%f %e\n", 100/k,a[k])}}' |
sort -k1,1n > ${maxerrordata}

maxfactor=$(awk '/^0.10/{print $2}' ${maxerrordata})
ploton --xl dx --yl "maximum relative error" --yf "%.1E" --logx --logy \
       --output "${maxerrorimg}" \
       "#1 u 1:2 with linespoints, ${maxfactor}*(x/0.1)**4, ${maxfactor}*(x/0.1)**5" ${maxerrordata} |
xargs cp2server
