#!/bin/zsh

logfile=log
errordata=mass-error.dat
errorimg=img/mass-error.pdf

make clean
rm -f ${log} ${errordata}

docker run -it --rm -v $PWD:/work -u $UID:$GID ishiy1993/formura-bin ./run-100-1000

gnuplot <<END
    set term pdf
    set output "${errorimg}"

    set logscale x
    set logscale y

    set format y "%.1E"

    set xlabel "dx"
    set ylabel "total mass error"

    f(x) = a*x**b
    a = 1
    b = 4
    fit f(x) "${errordata}" u 1:4 via a,b

    plot "${errordata}" u 1:4 with linespoints, 5*10**(-7)*x**4, 0.5*x**10
END

cp2server ${errorimg}

ls data/* | grep "100.dat" | xargs grep "." |
awk '{print $1,sqrt(($5-$2)^2)/$5}' |
tr ':' ' ' | sed 's;.*/;;' | sed 's/-.*dat//' |
awk '{if(a[$1] < $3){a[$1]=$3}}END{for(k in a){printf("%f %e\n", 100/k,a[k])}}' |
sort -k1,1n > max-error.dat

ploton --xl dx --yl "maximum relative error" --logx --logy '$1 u 1:2 with linespoints, 0.06*x**4, 0.6*x**5' max-error.dat | xargs cp2server
