#!/bin/bash

scheme=${1:?Need a scheme name}
t=${2:?Need time}
collum=${3:-2}
fmt=${4:-png}

ylb=$(echo ${collum} | awk '$1==2{print "dens"}$1==3{print "mass"}$1==4{print "energy"}$1==5{print "velocity"}$1==6{print "pressure"}$1==7{print "sound speed"}')
gnuplot -p <<END
set term ${fmt}
set output "img/${scheme}-${t}-${collum}.${fmt}"
set style data linespoints; set title "t=${t}"
set xlabel "x"
set ylabel "${ylb}"

plot "data/${scheme}-${t}.dat" u 1:$collum title "numerical(${scheme} scheme)", "data/exact-${t}.dat" u 1:$collum title "exact"
END
