#!/bin/bash

TARGET=${1:?Need a target}
vis=${2:?Need a viscocity}
n=${3:-16}

echo ${TARGET}
echo ${vis}
echo ${n}

sed -i -E "s/(TARGET :=).*/\1 ${TARGET}/" Makefile
sed -i -E "s/(double :: vis = ).*/\1${vis}/" ${TARGET}.fmr
sed -i -E "s/(double a = ).*/\1${vis};/" ${TARGET}-main.cpp
grep 'double :: vis' ${TARGET}.fmr
grep 'double a' ${TARGET}-main.cpp

echo $(date +"%F %T") $(grep "intra" ${TARGET}.yaml)
make clean
time make ${TARGET}.c
time make -j ${n}
time make run
echo $(date +"%F %T")
